### ISSUE TITLE
Error While Running Simulation 

### ISSUE THREAD

**Issue by LogToIn** [ravenusa/IoT-SmartHome#1]
sketch.ino: In function 'void getPirValue()':
sketch.ino:245:11: error: 'class BlynkWifi' has no member named 'notify'
     Blynk.notify("Ada Gerakan !!");

Blynk.notify error

**Comment by ravenusa** [comment]
Okey Lets Check it

**Comment by ravenusa** [comment]
refresh your simulation link and try again, I've replaced the library blink

![image](https://github.com/ravenusa/IoT-SmartHome/assets/80948124/20cda67e-6a34-4a51-98b2-b67229e52a77)
