### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by LogToIn** [ravenusa/IoT-SmartHome#2]
Does this also require a mosquitto server as well?

**Comment by ravenusa** [comment]
Yes, a mosquitto server is required to display data acquisition from both sides

**Comment by ravenusa** [comment]
You can add the mosquitto server to the following variables

![image](https://github.com/ravenusa/IoT-SmartHome/assets/80948124/ba93f94d-11bd-44ba-99cb-1b7371b88c21)

**Comment by LogToIn** [comment]
ok thanks for answering
